syntax on
colors elflord
set cin
set noexpandtab
set backspace=indent,eol,start
set cpoptions=aABceFs
set ul=1000
set ruler
set mouse=a

set linebreak
set showbreak=..
set scrolloff=4

"set backup
"set backupcopy=yes,breakhardlink

set backupskip=/tmp/*,svn-commit.tmp

filetype plugin indent on

imap ( ()<Left>
imap [ []<Left>

map <F2> :w<CR>
imap <F2> <Esc>:w<CR>
imap <F10> <Esc>:q<CR>
map <F10> :q<CR>
imap [24;5~ <C-R>=strftime("%Y-%m-%d")"<CR>
imap <F12> <C-R>=strftime("%Y-%m-%d")"<CR>
imap <C-F10> <Esc>:wq<CR>
map <C-F10> :wq<CR>
map <S-F2> <Esc>:NERDTreeToggle<CR>

" Remap a misspelt :wq.
command Wq wq

" Make sure to center screen upon navigating across search terms and
" paragraphs.
nnoremap N Nzz
nnoremap n nzz
nnoremap { {zz
nnoremap } }zz

"--------------------
" Function: Open tag under cursor in new tab
" Source:   http://stackoverflow.com/questions/563616/vimctags-tips-and-tricks
"--------------------
map <C-\> :tab split<CR>:exec("tag ".expand("<cword>"))<CR>

if has("gui_running")
	au BufRead,BufNewFile *.go set encoding=utf8
else
	au BufRead,BufNewFile *.go set encoding=utf8 termencoding=latin1
endif

highlight WhitespaceEOL ctermbg=red guibg=red
match WhitespaceEOL /\s\+$/
